version: '3.9'

services:


  jaeger-api:
    image: jaegerapi
    build:
      context: ./
      dockerfile: dockerfile



    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    ports:
      #- "7074-7076:7076"
       - 7080:7080

    volumes:
      - /data/compose-app
    #networks:
      #- boanetwork


### put all the networks here
#networks:
  #boanetwork:
networks:
  default:
    name: elastic
    external: false

  