version: '3.9'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - node.roles=master,data_content,data_hot,remote_cluster_client
      - path.repo=/usr/share/elasticsearch/snapshots
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4Gb
    volumes:
      - hot_data:/usr/share/elasticsearch/data
      - snapshots:/usr/share/elasticsearch/snapshots
    ports:
      - 9200:9200
    #networks:
      #- elastic
 
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - node.roles=master,data_warm,remote_cluster_client
      - path.repo=/usr/share/elasticsearch/snapshots
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4Gb
    volumes:
      - warm_data:/usr/share/elasticsearch/data
      - snapshots:/usr/share/elasticsearch/snapshots
    #networks:
      #- elastic
 
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - node.roles=master,data_cold,remote_cluster_client
      - path.repo=/usr/share/elasticsearch/snapshots
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4Gb
    volumes:
      - cold_data:/usr/share/elasticsearch/data
      - snapshots:/usr/share/elasticsearch/snapshots
    #networks:
      #- elastic
 
  es04:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es04
    environment:
      - node.name=es04
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - node.roles=master,data_frozen,remote_cluster_client
      - path.repo=/usr/share/elasticsearch/snapshots
      - xpack.searchable.snapshot.shared_cache.size=10%
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4Gb
    volumes:
      - frozen_data:/usr/share/elasticsearch/data
      - snapshots:/usr/share/elasticsearch/snapshots
    #networks:
      #- elastic
 
  kib01:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200","http://es04:9200"]'
    mem_limit: 4Gb
    #networks:
      #- elastic
  
volumes:
  hot_data:
    driver: local
  warm_data:
    driver: local
  cold_data:
    driver: local
  frozen_data:
    driver: local
  snapshots:
    driver: local
 
networks:
  default:
    name: elastic
    external: false